// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: data.sql

package database

import (
	"context"
)

const addChar = `-- name: AddChar :one
INSERT INTO
    chars (val, word_id)
VALUES
    (?, ?)
RETURNING
    id, val, word_id
`

type AddCharParams struct {
	Val    string
	WordID int64
}

func (q *Queries) AddChar(ctx context.Context, arg AddCharParams) (Char, error) {
	row := q.db.QueryRowContext(ctx, addChar, arg.Val, arg.WordID)
	var i Char
	err := row.Scan(&i.ID, &i.Val, &i.WordID)
	return i, err
}

const addDocument = `-- name: AddDocument :one
INSERT INTO
    documents (name)
VALUES
    (?)
RETURNING
    id, name
`

func (q *Queries) AddDocument(ctx context.Context, name string) (Document, error) {
	row := q.db.QueryRowContext(ctx, addDocument, name)
	var i Document
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const addWord = `-- name: AddWord :one
INSERT INTO
    words (val, doc_id)
VALUES
    (?, ?)
RETURNING
    id, val, doc_id
`

type AddWordParams struct {
	Val   string
	DocID int64
}

func (q *Queries) AddWord(ctx context.Context, arg AddWordParams) (Word, error) {
	row := q.db.QueryRowContext(ctx, addWord, arg.Val, arg.DocID)
	var i Word
	err := row.Scan(&i.ID, &i.Val, &i.DocID)
	return i, err
}

const getWordsFreq = `-- name: GetWordsFreq :many
SELECT
    w.val AS word,
    COUNT(*) AS freq
FROM
    words w
GROUP BY
    w.val
ORDER BY
    freq DESC
`

type GetWordsFreqRow struct {
	Word string
	Freq int64
}

func (q *Queries) GetWordsFreq(ctx context.Context) ([]GetWordsFreqRow, error) {
	rows, err := q.db.QueryContext(ctx, getWordsFreq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWordsFreqRow
	for rows.Next() {
		var i GetWordsFreqRow
		if err := rows.Scan(&i.Word, &i.Freq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
