// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Document struct {
	ID   int64
	Name string
}

type Stopword struct {
	ID  int64
	Val string
}

type Word struct {
	ID    int64
	Val   string
	DocID int64
}
