// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Char struct {
	ID     int64
	Val    string
	WordID int64
}

type Document struct {
	ID   int64
	Name string
}

type Word struct {
	ID    int64
	Val   string
	DocID int64
}
